apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    -
      targetPort: 80          #this is the port owned by the pod where the destination lives
      port: 80                #this is the port owned by the K8s service; this field is mandatory
      nodePort: 30008         #this is the port used by the K8s node itself
  selector:
    app: frontend